version: "3.0"

services:
  chatbot:
    container_name: ChatBot
    build:
      context: .
      dockerfile: dockerfile
      args:
        ARTIFACTORY_AUTH: ${ARTIFACTORY_AUTH}
        VITE_AZURE_OPENAI_ENDPOINT: ${VITE_OPENAI_ENDPOINT}
        VITE_AZURE_OPENAI_API_KEY: ${VITE_OPENAI_KEY}
        VITE_BASE_PATH: ${VITE_BASE_PATH}
        VITE_OPENAI_API_VERSION: ${VITE_OPENAI_API_VERSION}
        VITE_IS_AZURE: ${VITE_IS_AZURE}
        VITE_AZURE_DEPLOYMENTS: ${VITE_AZURE_DEPLOYMENTS}
    image: ${DOCKER_REGISTRY}/azureopenaichatbot:latest
